export enum Color {
  PRIMARY = "var(--primary)",
  PRIMARY_LIGHT = "var(--primary_light)",
  SECONDARY = "var(--secondary)",
  BACKGROUND_PRIMARY = "var(--background_primary)",
  BACKGROUND_PRIMARY_DARK = "var(--background_primary_dark)",
  GRAPHITE = "var(--background_graphite)",
  ERROR = "var(--error)",
  LIGHT = "var(--light)",
  TEXT_PRIMARY = "var(--text_primary)",
  WHITE = "white",
  GREEN = "#00A340",
  YELLOW = "#F3A608",
  ORANGE = "#F45D2D",
}
